### ISSUE TITLE
BUG: Google login encounters error on redirect url (LL-261)

### ISSUE THREAD

**Issue by aematei** [luminosityleds/client#28]
<img width="1153" alt="image" src="https://github.com/luminosityleds/client/assets/25559473/55065f67-9dad-4e51-b814-3e7cfb7b6ef0">

When attempting to log in via Google SSO, I am encountering the above error (Error 400: redirect_uri_mismatch). 
To recreate this error:
1. run a GitHub codespace through your local VSCode application
2. clone the LL server repo into the parent directory of the LL client one on in your codespace (`../server`)
3. aquire the most recent `server/src/routes/.env` file (ask @erikajledesma if you don't know where it get it)
4. run `docker compose up --build` in the terminal in `/server`
5. make sure the `google-1` service is running on port `5000`. You may need to kill the process and run the above command again.
6. in `/client`, run `nom run dev` or what ever command starts the `vite` development server
7. make sure the `vite` server is running on port `3000`
8. go to `http://localhost:3000/login` and click on the Google SSO button
9. you should get the same error as the picture at the top of this description

**Comment by aematei** [comment]
@erikajledesma this might be a part of the issue: https://www.googlecloudcommunity.com/gc/Cloud-Hub/Authorized-Javascript-Origins-on-my-OAuth-Client-IDs-are-not/m-p/550360

**Comment by erikajledesma** [comment]
@aematei in your GoogleLogin.tsx file can you change line 10 to this:
`const google_response = await axios.get("https://www.googleapis.com/oauth2/v3/userinfo",`

**Comment by aematei** [comment]
Thanks @erikajledesma! Here is the solution that worked on my end:

1. Add both `http://localhost` and `http://localhost:3000` to Authorized JavaScript origins on the Google Cloud console under 'credentials'
2. Add `<meta name="referrer" content="strict-origin-when-cross-origin" />` under `<Head>` in `index.html`
